### ISSUE TITLE
exigence du client 

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#175]
sur la facture on doit afficher toute les informations du client nis nif rc et adresse ... sauf le téléphone 
il faut aussi afficher le montant en lettre sur la facture

on doit ajouter la facture pro forma
et le bon de livraison qui ressemble a la facture mais sans les prix 
dans le bon de livraison on doit ajouter un champ observation pour chaque produit qui sera saisi ou laisser vide par l'utilisateur

**Comment by lotfiAliane** [comment]
petite correction pour le BL Genre je suis un Client et je fais une commande de 100 table donc tu me fais la facture et la quantité sera décrémenté aprés mon livreure viens prendre que 50 table donc tu me fais un BL mais sans décrémenté avec un champ de saisie libre pour chaque produit et et a chaque fois qu'il reviens tu me fais le BL selon la quantité qu'il va prendre, donc le BL n'affecte pas les calcule du logiciel c'est juste pour la route on va dire

**Comment by lotfiAliane** [comment]
réglé
