### ISSUE TITLE
Stat 

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#178]
Graph Les 8 Produits en rupture de stock
Pour la quantité pk elle est présentée en gris faut enlever hadak le caré gris 
![ici](https://cloud.githubusercontent.com/assets/20946708/19064740/150c5c2c-8a07-11e6-9d09-d03f4361bdf8.JPG)

**Comment by lotfiAliane** [comment]
ping charaf

**Comment by CharafLachachi** [comment]
impossible de l'enlever
