### ISSUE TITLE
Probleme + de détails

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#185]
La petite bouton + raha déconné bezzaf w matetla3ch w tableau yebka y bougi si c possible de revoir si c un blem de code merci

**Comment by ayoubensidhoum** [comment]
l3afsa charaf quand le tableau maykounch fih bezzaf alors ykoun sguir 
donc le + détails fih une fenetre dakhel le tableau matbanch fih ki ykoun sguir

**Comment by lotfiAliane** [comment]
réglé

**Comment by ayoubensidhoum** [comment]
pas encore : Liste client

**Comment by lotfiAliane** [comment]
réglé
