### ISSUE TITLE
facture achat 

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#186]
quand je valide, aucun message ne s'affiche et il imprime un ticket. il faut enlever l'impression f l'achat et afficher facture ajouter avec succès

sto le box de la quantité seghrou chwiya pr que les boutons - + yjiw sur la meme ligne

**Comment by lotfiAliane** [comment]
pr le box quantité je le controle pas, pour le reste c'est réglé
