### ISSUE TITLE
Facture de vente

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#188]
La somme prix en Lettre manque dinars a la fin 
faut revoir dessign

**Comment by lotfiAliane** [comment]
quand tu la termine remplace la par, l’existante essaye de gardé le meme nom, aussi rajoute une phrase normalement rida t'as passé des exmple de facture tt en bas c'est marqué " somme arrété ou un truc du genre c'est la qu'il faut metre le montant lettre  "

**Comment by lotfiAliane** [comment]
quand tu termine close
