### ISSUE TITLE
modifié facture chachat

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#191]
faut mettre à jour view modifié 
tableau
aussi fourisseur date achat etc ...

**Comment by ayoubensidhoum** [comment]
pour modification d'une facture d'achat 
le tableau khasou yji le meme kima ajouter facture achat c a d (les mm colonne avec mm en tete)
aussi la selection d'un fournisseur khasha tkou f modification d'une achat 
la date aussi

**Comment by ayoubensidhoum** [comment]
va voir modifier une facture de vente w chouf

**Comment by lotfiAliane** [comment]
réglé
