### ISSUE TITLE
alerte

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#192]
message de modification avec succès d'ue facture proformat et de vente aussi bon de livraison

**Comment by lotfiAliane** [comment]
réglé

**Comment by ayoubensidhoum** [comment]
pas encore soit prudent svp

**Comment by ayoubensidhoum** [comment]
pour livraison modifié pas modifier et facture de vente modifiée supprimée avec succès
