### ISSUE TITLE
facture de vente proformat bon

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#195]
faut ajouté un message si aucun produit n'est sélectionne 
Veuillez ajouter un produit s'il vous plait

**Comment by lotfiAliane** [comment]
réglé

**Comment by ayoubensidhoum** [comment]
Pour facture d'achat aussi s'il vous plait hna aussi faut tester si fournisseur et sélectionner ou pas

**Comment by ayoubensidhoum** [comment]
Si c'est possible d'jouter d'achat achat f view

**Comment by lotfiAliane** [comment]
on peut en ajouté une facture sans fournisseur !

**Comment by lotfiAliane** [comment]
!!!
