### ISSUE TITLE
est ce que

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#197]
ajouter un message f achat si fournisseur machi selectionné et Produit

Veuillez sélectionner un fournisseur s'il vous plait

Veuillez sélectionner un produits'il vous plait

**Comment by lotfiAliane** [comment]
parfois on pas a saisir le nom du fournisseur donnc il laisse vide et f l'affichage il aura Divers, plus tu laisse la liberté a l'utilisateur mieux c'est
