### ISSUE TITLE
modifier produit

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#206]
bouton valider dans view edit produit faut la remplacer comme les autres stp

**Comment by lotfiAliane** [comment]
réglé

**Comment by ayoubensidhoum** [comment]
c pas réglé lotfi

**Comment by ayoubensidhoum** [comment]
![Uploading image.png…]()

**Comment by ayoubensidhoum** [comment]
tu trouve que c réglé ?

**Comment by lotfiAliane** [comment]
comment il doit etre ?

**Comment by ayoubensidhoum** [comment]
![untitled](https://cloud.githubusercontent.com/assets/20946708/19407870/9a088ea8-92a6-11e6-90ab-15d623e9b509.jpg)
