### ISSUE TITLE
erreur facture achat

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#207]
mon scénario 
produit de 100 quantité
j'ai ajouté une facture avec 20 quantité de ce produit résultat produit 120 quantité
j'ai modifié cette facture avec 30 quantité au lieu du 20 donc normalement résultat produit 130 quantité
résultat 100 quantité ERREUR !!!!!!

**Comment by lotfiAliane** [comment]
réglé
