### ISSUE TITLE
Quantité Produit dans une vente 

### ISSUE THREAD

**Issue by CharafLachachi** [CharafLachachi/OneRakTa3ref#216]
si j'ajoute une vente avec une quantité supérieure a celle du stock le stock devient négatif

**Comment by lotfiAliane** [comment]
réglé

**Comment by CharafLachachi** [comment]
Un autre problème 
scénario : 
j'ai ajouté une vente avec un produit qui avait 15 unités en stock et dans la vente j'ai mis quantité à 16 la vente a été ajouté. alors qu'il fallait afficher une alerte comme quoi la quantité est supérieure au stock

**Comment by lotfiAliane** [comment]
réglé mais éssaye de revoir balek j'ai oublié quelque chose

**Comment by CharafLachachi** [comment]
le probleme qui se pose mnt quand il affiche automatiquement la quantité resté et j'essaie de la modifier manuellement en écrivant dans le textbox l'alerte s'affiche tjr meme si la quantité est inférieure

**Comment by lotfiAliane** [comment]
j'ai éssayé le meme scénario que tu viens de me dire et ça marche bien pour moi réessaye
