### ISSUE TITLE
Vue

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#217]
il faut enlevé reste à payer .... de la vue BL et facture proforma

**Comment by ayoubensidhoum** [comment]
bien dit pour les factures proforma faut enlever payer w tmanyik
w bl faut enlevrer prix

**Comment by lotfiAliane** [comment]
supossant qu'il lui demande chehahl tjini il va lui dire attend je vais ouvrir la vente w simulé ou mieux encore il ramène la grande la calculatrice -_-

**Comment by fcbrida** [comment]
non malek je parle de reste à payer et versé kich ch3al tjini il va pas payer fel facture proforma

**Comment by lotfiAliane** [comment]
oui mais regarde sque ayyoub demande !!

**Comment by fcbrida** [comment]
il parle du BL si il a demandé qu'il n'y a pas de prix logiquement makench total faut voir avec le client dans ce cas à moins que tu affiches le total sur la vue mais pas sur l'imprimable

**Comment by lotfiAliane** [comment]
aussi en faisant ces changement je risque de provoqué des bug, vaut mieux bien testé trés bien testé, on doit vérifié s'il ya des bug, des érreurs de calcules c'est important !! faite des testes et non des suggestion sauf dans des cas vraiment inapproprié  s'il vous plait, je comprend que vous voulez qu'on fasse un bon produit moi aussi d'ailleurs mais la on est a court de temps et le client est patient avec nous mais ça patience a ces limites !

**Comment by ayoubensidhoum** [comment]
que ce que j'ai dis j'ai demander juste de payer rendre et tt mayahtajhomch
aussi il va pas demandé chehal tjini f bl puisque il a déja acheté les produit alors matanahch rassek 
w proforma jai demandé juste d'enlevé rendre versé
