### ISSUE TITLE
les code automatique

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#220]
je t'ai demandé de voir les code auto 👍

Client : C/Num/Année
Fournisseur : F/Num/Année
F.V : F.V/Num/Année
F.P : F.P/Num/Année
B.L : B.L/Num/Année
F.A : F.A/Num/Année

C mieu meme f exemple de ça facture et bon de livraion ando num année

**Comment by lotfiAliane** [comment]
impossible
