### ISSUE TITLE
selectionne client fournisseur

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#222]
dans tt les vues ( 7 vues)
ajout facutre de ventre/proforma
modification facture de vente
modification facture proforma
ajout bon de livraison
modification bon de livraison
ajout facture achat
modification facture achat

un probleme lors de l'affichage des informations reliées au champ (client/fournisseur) : 
défois il affiche prénom a la place de adresse ou tél 
défois la liste contient que les noms pas nom et prénom 

a voir ça stp 

dans les 7 vues j'ai essayer de régler l'interface client code adresse tél essaye de lui affecté les bons valeurs et merci

**Comment by lotfiAliane** [comment]
fallais pas touché a ça

**Comment by lotfiAliane** [comment]
au moin me le demandé

**Comment by lotfiAliane** [comment]
et juste une remarque c'etait bcp mieux avant donc merci de les rendre comma li kanou quand tu termine tu close

**Comment by lotfiAliane** [comment]
et ne remplace pas les fichier j'ai effectuer pas mal de changement !!!! donc arrangé sque ta causé manuellement
