### ISSUE TITLE
modification type produit 

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#226]
![image](https://cloud.githubusercontent.com/assets/20947094/19733367/131d91de-9ba4-11e6-9e38-79cd6305cb6b.png)
le scénario :
j'ai ajouté un type "ancre"
j'ai ajouté un autre type "ancreee"
j'ai modifié le type "ancreee" pour le rendre "ancre"
quand j'ai validé il m'a donné cette erreur 
donc il faut gérer l’exception en cas de modification

**Comment by lotfiAliane** [comment]
réglé
