### ISSUE TITLE
modification produit

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#228]
![image](https://cloud.githubusercontent.com/assets/20947094/19733856/a686980c-9ba5-11e6-8f5d-3e55aa397e74.png)
scénario :
j'ai ajouté un produit CX4300 de type ancreee
j'ai ajouté le même produit mais de type ancre

j'ai modifié le type du premier produit en ancre, est il normal d'avoir deux référence interne identique ?

**Comment by lotfiAliane** [comment]
c'est ce qu'il a demandé la première lettre du type suivie de son ordre
