### ISSUE TITLE
achat

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#230]
![image](https://cloud.githubusercontent.com/assets/20947094/19734797/36204c12-9ba9-11e6-9bb6-6829eaf7f602.png)
elle est vraiment bien hadi yaatik saha, ajoute la sur achat aussi

je trouve qu'il faut remplacer le texte par liste des produits car il peut aussi sélectionner un produit à l'aide du code barre

**Comment by lotfiAliane** [comment]
je l'ai changé un peu malheureusement :/ ! réglé
