### ISSUE TITLE
vente Erreur de calcul

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#234]
scénario : 
j'ai ajouté un produit avec un stock de 2000 unités 
dans la facture j'ai ajouté 2000 puis j'ai cliqué sur + il affiche un message que comme quoi la quantité demandé est supérieur au stock mais il ajoute quand même son prix ( pour résumé il affiche le prix de 2001 unités)

**Comment by fcbrida** [comment]
![image](https://cloud.githubusercontent.com/assets/20947094/19735684/e587b5de-9bac-11e6-9add-cf24ab80af07.png)

**Comment by fcbrida** [comment]
quand je valide avec cette erreur voilà ce que j'ai 
![image](https://cloud.githubusercontent.com/assets/20947094/19735764/3452eef4-9bad-11e6-8c80-7effadd449a6.png)

**Comment by lotfiAliane** [comment]
réglé
