### ISSUE TITLE
V2.0 Ajout Vendre

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#241]
Si par exemple j'ai un ajouter un produit avec une quantité c ok
Mais quand j'ajout le mm produit f la case selectionner un produit un petit message yetla3 
![capture1](https://cloud.githubusercontent.com/assets/20946708/20919369/c4841a6c-bb9b-11e6-87f7-802c3f285be4.JPG)

**Comment by CharafLachachi** [comment]
j'ai enlevé une alerte mais je ne sais pas si c'est la bonne tu dois revérifier

**Comment by ayoubensidhoum** [comment]
C réglé
