### ISSUE TITLE
V2.0 Ajouter Achat

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#244]
Le scénario :
- Sélectionner le produit : A9+
- Modifier la quantité : 50
Ajouter.
Erreur.
![achat](https://cloud.githubusercontent.com/assets/20946708/20919888/2e12b608-bb9e-11e6-85dc-23b4c76512ff.JPG)

**Comment by CharafLachachi** [comment]
résolu
