### ISSUE TITLE
V2.0 Ajouter Achat

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#245]
En faite le truc c'est que y a un problème avec l'ajout des factures d'achat.

**Comment by ayoubensidhoum** [comment]
Et il met à jour la quantité du Produit ajouté

**Comment by ayoubensidhoum** [comment]
Il ajout la facture en faite mais l'erreur pk !!!!

**Comment by CharafLachachi** [comment]
résolu

**Comment by CharafLachachi** [comment]
résolu
