### ISSUE TITLE
V2.0 Liste Type Produit

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#248]
Quand je suis sur la vue Type Produit et je veux créer un Type Produit à partir du bouton (raccourci) en Haute Erreur 
![typeproduit1](https://cloud.githubusercontent.com/assets/20946708/20968671/d4e8a4d2-bc85-11e6-9ad9-c201d93b83b6.JPG)

**Comment by ayoubensidhoum** [comment]
Ajouter un type produit marche pas !!

**Comment by CharafLachachi** [comment]
résolu
