### ISSUE TITLE
V2.0 Ajout Client

### ISSUE THREAD

**Issue by ayoubensidhoum** [CharafLachachi/OneRakTa3ref#249]
Probleme ajouter client erreur 
![client](https://cloud.githubusercontent.com/assets/20946708/20969790/e84068bc-bc8a-11e6-8956-702002dc25bc.JPG)

**Comment by ayoubensidhoum** [comment]
rah yenzad bessah voila erreur ki tu valide l'ajout

**Comment by CharafLachachi** [comment]
résolu
