### ISSUE TITLE
GESTION DES VENTES [Ajouter facture de vente]

### ISSUE THREAD

**Issue by mosari1** [CharafLachachi/OneRakTa3ref#260]
"Merci d'ajouter au minimum un produit", ça ne marche pas lors de l'ajout et je ne vois pas ou se trouve mon erreur, j'ai ajouté le produit.

**Comment by lotfiAliane** [comment]
je pense que t'as pas ajouté de produit, le fait de sélectionné un produit dans la le drop down ne suffit pas faut appuyer ensuite sur entrer
!

**Comment by mosari1** [comment]
Même si je fais cela ça marche, et si ça marchait ça n'aurait pas été forcément intuitif, je pense qu'il peut y avoir une autre solution

**Comment by lotfiAliane** [comment]
c'est système qui fonctionne avec le lecteur de  code barre le drop-down est une alternative ! et pour moi ça fonctionne lorsque j'ajoute un produit, merci d'envoyé une capture avant la validation et une autre aprés la validation
