### ISSUE TITLE
V2 calcul de gain

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#265]
![image](https://cloud.githubusercontent.com/assets/20947094/21424709/cf568424-c844-11e6-868b-70b5163c36cd.png)
j'ai toujours ce problème je ne sais pas pourquoi !! il faut trouver une solution

**Comment by CharafLachachi** [comment]
j'ai trouver une faille utilise seulement la souris pour changer de field dans mon cas quand j'utilise tab pour accéder au field suivant je n'ai pas le -:(

**Comment by CharafLachachi** [comment]
normalement c'est résolu mais revérifier
