### ISSUE TITLE
V2 Facture de vente 

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#268]
![image](https://cloud.githubusercontent.com/assets/20947094/21425423/53cc83ee-c849-11e6-8381-4cf19fbe17b9.png)
je suis connecté autant que vendeur, j'ai cliqué sur le radio facture de vente il m'a donné la possibilité de faire une facture proforma

**Comment by CharafLachachi** [comment]
résolu
