### ISSUE TITLE
V2.0 vente

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#275]
très grand problème pour moi :D
j'ai mis la quantité de 100 alors que dans le stock j'ai que 22 il m'a bel et bien affiché que la quantité dépasse, mais dans les calculs il garde tjr le total avec le stock de 100
![image](https://cloud.githubusercontent.com/assets/20947094/21467054/96184ad4-c9df-11e6-8f6a-2c683db3f503.png)

**Comment by lotfiAliane** [comment]
réglé
