### ISSUE TITLE
V2.0 graphe

### ISSUE THREAD

**Issue by fcbrida** [CharafLachachi/OneRakTa3ref#277]
![image](https://cloud.githubusercontent.com/assets/20947094/21467472/8382699e-c9ef-11e6-9294-71a9c7898f17.png)
il n'affiche rien en novembre alors que j'ai deux vente en ce mois
![image](https://cloud.githubusercontent.com/assets/20947094/21467477/a168c55c-c9ef-11e6-93cc-f95028510ff5.png)

**Comment by CharafLachachi** [comment]
résolu
